version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:15"
    labels:
      - "dependencies"
  - package-ecosystem: "gomod"
    # Setting open-pull-requests-limit to 0 means that dependabot will not
    # update regular dependencies on this target branch, but still provide
    # security updates for our gomod dependencies
    open-pull-requests-limit: 0
    target-branch: "release-1.0"
    directory: "/"
    schedule:
      interval: "daily" # it's UTC, so I just want to check if it properly triggers today, will change this when checked
      time: "17:15"
    labels:
      - "dependencies/security"